### ISSUE TITLE
[BUG] Unable to connect to Keycloak when not on port 9001 

### ISSUE THREAD

**Issue by rsf123** [Cingulara/openrmf-docs#219]
**Describe the bug**
Unable to connect to keycloak server when server is not running on port 9001.  Keycloak server is moved to port 8080 and main openrmf-web is moved to port 80.  .ENV file is edited to point to port 8080 for authentication.

**To Reproduce**
1. Edit docker compose file for main application and change the exposed port for openrmf-web to 80 (line now reads 80:8080)
2. Edit docker compose for keycloak server and change exposed port from 9001 to 8080 (line now reads 8080:8080)
3. Edit .ENV file and change port 9001 to port 8080
4. Start application up

**Expected behavior**
Expected behavior is that when performing a log in the openrmf-web will redicrect to keycloak on port 8080 instead of port 9001.  openrmf-web is still redirecting to port 9001 indicating that either the .ENV is not being read, or there is a hard coded value somewhere.  I am able to MANUALLY point to keycloak running on port 8080 so the docker compose files are correct.

**Desktop (please complete the following information):**
ubuntu

**Additional context**
Noticed there were other bugs reported on this type of issue that were closed, but it wasn't clear if they were closed/unresolved or closed/resolved.

**Comment by Cingulara** [comment]
This is not a bug. This is by design and is noted in a few places. If you wish to run OpenRMF and Keycloak on other ports you have to setup the UI as well as the backend. The .env file is for the backend APIs. The auth.js is how you connect to Keycloak via the front end. You have to get a JWT via the front end, and then use it to call APIs on the backend. That is the auth.js part. The JWT on the APIs is validated behind the scenes, using the info in the .env.

Look at the https://cingulara.github.io/openrmf-docs/domainkeycloak.html documentation we put out. The auth.js in the Open Source app assumes port 9001. But you can overwrite that with a file mounted into the container and make it point to wherever you wish it to be. I do something similar for K8s using the Helm Chart setup. You make your own auth.js file, look at the docs here or the actual source code https://github.com/Cingulara/openrmf-web/blob/master/js/auth.js. You can see the hard coded 9001 there. 

So to do this, you can create an auth.js file, mount it into the OpenRMF stack like the documentation talks on just below the NGINX configuration file, and then bring up the OpenRMF stack. Log in, clear cache, and see if it redirects to your :8080 setup.

**Comment by rsf123** [comment]
Was able to do this and get the services to set up and authenticate.  Running into a new issue, now with access through the template-api.  Will start a new question to keep things clean.

**Comment by Cingulara** [comment]
ok good deal!
