### ISSUE TITLE
[BUG] Severity Checklist Filter doesn't seem to filter down results for Cat I only.

### ISSUE THREAD

**Issue by phopfner-dli** [Cingulara/openrmf-docs#269]
**Describe the bug**
This is against v1.7.2 of the OpenRMF open-source product.   It appears that on the "System Package Information and Checklists" page under the "Checklist Filter", there are controls to filter the checklist for Status or Severity.   In my testing, it seems that the Severity filter doesn't seem to actually filter anything.  I select only "High (Cat 1)" and then Apply.  The results in the Checklist below don't change - it still shows the entire list of systems.  I.e., the Sev filter doesn't seem to filter anything.

**To Reproduce**
- Load a System Package with a small number of Cat 1s
- Go to that System Package
- Under "Checklist Filter", select "High (Cat 1)" only (clear the Med/Low checkmarks
- Click Apply.
Note that the checklist on the bottom doesn't seem to filter down to just the systems with Cat 1 issues.

**Expected behavior**
Only Cat 1 issues should be shown if only the Cat 1 Severity is selected

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser Chrome
 - Version 1.7.2

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by Cingulara** [comment]
If you only select CAT 1, then **_any_** Not a Finding, Open, N/A or Not Reviewed that is a High/CAT 1 anywhere in the checklist regardless of status (because all are checked) will trigger the checklist to show. This depends on the types of checklists you have loaded of course.  I put a few scenarios down below. 

I have 39 checklists loaded w/o all options selected:
![image](https://user-images.githubusercontent.com/46137145/168859043-0d8c246d-63cc-422b-8a2a-96922e492323.png)

1st scenario:
I have just CAT 1 checked. So any checklist that has any CAT 1 item, regardless of its current status, will show up.  When I do that, my 39 are now only 28 because I have some checklists that only have CAT 2 and CAT 3 items in them. They have 0 CAT 1s regardless of status. 

![image](https://user-images.githubusercontent.com/46137145/168859265-c9ea1d4b-5c7a-4536-ab4f-d31d488ed21d.png)

**2nd scenario:**
If you select Open and CAT 1 / High, it filters correctly as pictured below. I only have 4 with CAT 1 highs open

![image](https://user-images.githubusercontent.com/46137145/168859387-9da53484-2603-4ed0-ae86-928dabbbf00a.png)

**_3rd scenario:_**
I want to show any checklists where something is set as Not Reviewed. I only had 3 and I knew I had 3. They are below as well. 

![image](https://user-images.githubusercontent.com/46137145/168859719-a1137133-078c-44c2-9bb2-9bf1fa77705d.png)


So it appears the filter is working as designed from what we have tested here.
