### ISSUE TITLE
[FEATURE]  Document installation for air-gapped environments

### ISSUE THREAD

**Issue by msmithkey** [Cingulara/openrmf-docs#79]
This looks like a fantastic tool and I would love to test it in my environment. Unfortunately it looks like there is no straightforward way to pull and install in an airgapped environment. I do not have admin access to an internet connected system and ingress policy dictates that I cannot prep dependencies on non-organization owned hardware. 

I imagine given the scope of this effort, this is not an uncommon case.

thank you

**Comment by Cingulara** [comment]
You can have docker, and docker-compose, on your not-on-the-internet computer. You need to get it there somehow on USB or DVD or something. But you can install it even if on Linux. 

You will need to pull images to run locally on the airgapped box, so off the top of my head you can do something like the following:
* on an Internet connection machine, run the "start.sh" from one of the releases
* this will run docker-compose and pull all relevant software container images
* you can use the `docker save -o xxxxxxxxxxx filename` type of command to save the image to a local file
* do this for all the openrmf-xxxxx images as well as the Mongo, Prometheus, Grafana, NATS images (if you want Prometheus and Grafana, otherwise comment them out)
* on the airgapped machine you can run `docker load -i xxxxxxxxxxxx` on each one to load that image file onto that machine
* do a `docker images | more` to see that they all loaded correctly
* run the ./start.sh on that airgapped machine 
* if the machine is connected to nothing, you may need to plug it into a switch, just to have it sense a network connection -- @degthat8412 I think had to do that...he can verify

@degthat8412 may have better ideas as well...

**Comment by Cingulara** [comment]
⬆️ This will let you copy the images to another machine and run the images you pulled from dockerhub.com if you are allowed to.

**Comment by Cingulara** [comment]
https://github.com/Cingulara/openrmf-docs/blob/develop/airgapped-install.md
